// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhlsvdxptkxulkodwfyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobHN2ZHhwdGt4dWxrb2R3Znl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDM5NjMsImV4cCI6MjA2NjAxOTk2M30.cqLyIlvGeFehS4pzEFCas4LXzc_HCKPIscrV97kUAjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);